//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProcessAWS
{
    using System;
    using System.Collections.Generic;
    
    public partial class News
    {
        public decimal NewsID { get; set; }
        public string Tittle { get; set; }
        public string Summary { get; set; }
        public string Content { get; set; }
        public int CategoryNewID { get; set; }
        public System.DateTime Date_Created { get; set; }
        public System.DateTime Date_Modify { get; set; }
        public short StatusID { get; set; }
        public Nullable<System.DateTime> Date_Publisher { get; set; }
        public Nullable<System.DateTime> DateForecast { get; set; }
        public Nullable<int> Languages_ID { get; set; }
        public string EDITTEDCONTENT { get; set; }
    
        public virtual CategoryNew CategoryNew { get; set; }
    }
}
